name: Blargg_cpu_instrs_07_jr_jp_call_ret_rst

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y pkg-config libasound2-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo run -p blargg_tests -- "tests/roms/cpu_instrs/individual/07-jr,jp,call,ret,rst.gb"
